<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employer extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'company_name',
        'contact_person',
        'contact_email',
        'contact_mobile',
        'min_travel_trade_experience_years',
        'desired_domestic_travel_expertise',
        'desired_hotel_car_hire_expertise',
        'desired_international_travel_expertise',
        'desired_visa_handling_expertise',
        'desired_tours_holiday_packages_expertise',
        'desired_accounting_expertise',
        'domestic_gds_itinerary',
        'domestic_pnr_adult',
        'domestic_pnr_child_infant',
        'domestic_senior_citizen_fares',
        'domestic_student_fares',
        'domestic_youth_special_fares',
        'domestic_fare_mask',
        'domestic_ticketing_gds',
        'domestic_gds_type',
        'domestic_lcc_websites',
        'domestic_supplier_portal',
        'domestic_supplier_portal_name',
        'hotel_bookings_india',
        'hotel_contact_direct',
        'hotel_consolidator_websites',
        'hotel_local_dmc',
        'car_hire_city',
        'car_hire_other_cities',
        'intl_gds_itinerary',
        'intl_pnr_child_infant',
        'intl_senior_citizen_fares',
        'intl_student_fares',
        'intl_youth_special_fares',
        'intl_fare_mask',
        'intl_gds_type',
        'intl_queue_pnrs',
        'intl_first_reissue',
        'intl_subsequent_reissue',
        'intl_ticket_refunds',
        'intl_hotac_rooms',
        'intl_group_pnr',
        'intl_issue_emd',
        'intl_standalone_emd',
        'intl_associated_emd',
        'visa_aware_procedures',
        'visa_handled_personally',
        'visa_in_department',
        'visa_handled_usa',
        'visa_handled_canada',
        'visa_handled_mexico',
        'visa_handled_brazil',
        'visa_handled_other_south_america',
        'visa_handled_uk',
        'visa_handled_ireland',
        'visa_handled_haj_umrah',
        'visa_handled_uae',
        'visa_handled_schengen_countries',
        'visa_handled_russia',
        'visa_handled_china',
        'visa_handled_vietnam',
        'visa_handled_cambodia',
        'visa_handled_hong_kong',
        'visa_handled_philippines',
        'visa_handled_singapore',
        'visa_handled_malaysia',
        'visa_handled_australia',
        'visa_handled_new_zealand',
        'visa_draft_cover_note',
        'tours_handle_packages',
        'tours_countries',
        'tours_worked_cost',
        'tours_handle_incentive_groups',
        'tours_handle_mice_groups',
        'tours_handle_cruise_pax',
        'acc_record_transactions',
        'acc_bank_cc_reconciliations',
        'acc_corporate_card_reconciliations',
        'acc_track_commissions',
        'acc_submit_invoices',
        'acc_manage_financial_records',
        'acc_software_excel_proficient',
        'acc_prepare_analyze_reports',
        'acc_ensure_compliance',
        'acc_manage_ap_ar',
        'acc_process_payroll_expenses',
        'acc_calculate_pay_taxes',
        'acc_coordinate_auditors',
        'acc_monitor_cashflow_forecast',
        'acc_reconcile_bsp',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'desired_domestic_travel_expertise' => 'boolean',
        'desired_hotel_car_hire_expertise' => 'boolean',
        'desired_international_travel_expertise' => 'boolean',
        'desired_visa_handling_expertise' => 'boolean',
        'desired_tours_holiday_packages_expertise' => 'boolean',
        'desired_accounting_expertise' => 'boolean',
        'domestic_gds_itinerary' => 'boolean',
        'domestic_pnr_adult' => 'boolean',
        'domestic_pnr_child_infant' => 'boolean',
        'domestic_senior_citizen_fares' => 'boolean',
        'domestic_student_fares' => 'boolean',
        'domestic_youth_special_fares' => 'boolean',
        'domestic_fare_mask' => 'boolean',
        'domestic_ticketing_gds' => 'boolean',
        'domestic_lcc_websites' => 'boolean',
        'domestic_supplier_portal' => 'boolean',
        'hotel_bookings_india' => 'boolean',
        'hotel_contact_direct' => 'boolean',
        'hotel_consolidator_websites' => 'boolean',
        'hotel_local_dmc' => 'boolean',
        'car_hire_city' => 'boolean',
        'car_hire_other_cities' => 'boolean',
        'intl_gds_itinerary' => 'boolean',
        'intl_pnr_child_infant' => 'boolean',
        'intl_senior_citizen_fares' => 'boolean',
        'intl_student_fares' => 'boolean',
        'intl_youth_special_fares' => 'boolean',
        'intl_fare_mask' => 'boolean',
        'intl_queue_pnrs' => 'boolean',
        'intl_first_reissue' => 'boolean',
        'intl_subsequent_reissue' => 'boolean',
        'intl_ticket_refunds' => 'boolean',
        'intl_hotac_rooms' => 'boolean',
        'intl_group_pnr' => 'boolean',
        'intl_issue_emd' => 'boolean',
        'intl_standalone_emd' => 'boolean',
        'intl_associated_emd' => 'boolean',
        'visa_aware_procedures' => 'boolean',
        'visa_handled_personally' => 'boolean',
        'visa_in_department' => 'boolean',
        'visa_handled_usa' => 'boolean',
        'visa_handled_canada' => 'boolean',
        'visa_handled_mexico' => 'boolean',
        'visa_handled_brazil' => 'boolean',
        'visa_handled_other_south_america' => 'boolean',
        'visa_handled_uk' => 'boolean',
        'visa_handled_ireland' => 'boolean',
        'visa_handled_haj_umrah' => 'boolean',
        'visa_handled_uae' => 'boolean',
        'visa_handled_russia' => 'boolean',
        'visa_handled_china' => 'boolean',
        'visa_handled_vietnam' => 'boolean',
        'visa_handled_cambodia' => 'boolean',
        'visa_handled_hong_kong' => 'boolean',
        'visa_handled_philippines' => 'boolean',
        'visa_handled_singapore' => 'boolean',
        'visa_handled_malaysia' => 'boolean',
        'visa_handled_australia' => 'boolean',
        'visa_handled_new_zealand' => 'boolean',
        'visa_draft_cover_note' => 'boolean',
        'tours_handle_packages' => 'boolean',
        'tours_worked_cost' => 'boolean',
        'tours_handle_incentive_groups' => 'boolean',
        'tours_handle_mice_groups' => 'boolean',
        'tours_handle_cruise_pax' => 'boolean',
        'acc_record_transactions' => 'boolean',
        'acc_bank_cc_reconciliations' => 'boolean',
        'acc_corporate_card_reconciliations' => 'boolean',
        'acc_track_commissions' => 'boolean',
        'acc_submit_invoices' => 'boolean',
        'acc_manage_financial_records' => 'boolean',
        'acc_software_excel_proficient' => 'boolean',
        'acc_prepare_analyze_reports' => 'boolean',
        'acc_ensure_compliance' => 'boolean',
        'acc_manage_ap_ar' => 'boolean',
        'acc_process_payroll_expenses' => 'boolean',
        'acc_calculate_pay_taxes' => 'boolean',
        'acc_coordinate_auditors' => 'boolean',
        'acc_monitor_cashflow_forecast' => 'boolean',
        'acc_reconcile_bsp' => 'boolean',
    ];
}