<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class JobSeeker extends Model
{
    use HasFactory;

    protected $fillable = [
        'given_name',
        'family_name',
        'dob',
        'address',
        'mobile_no',
        'personal_email',
        'total_experience',
        'current_city',
        'willing_to_relocate',
        'preferred_cities',
        'current_salary',
        'cv_path',

        // Add all your other form field names here
        'domestic_gds_itinerary',
        'domestic_pnr_adult',
        'domestic_pnr_child_infant',
        'domestic_senior_citizen_fares',
        'domestic_student_fares',
        'domestic_youth_special_fares',
        'domestic_fare_mask',
        'domestic_ticketing_gds',
        'domestic_gds_type',
        'domestic_gds_other_name',
        'domestic_lcc_websites',
        'domestic_supplier_portal',
        'domestic_supplier_portal_name',

        'hotel_bookings_india',
        'hotel_contact_direct',
        'hotel_consolidator_websites',
        'hotel_local_dmc',
        'car_hire_city',
        'car_hire_other_cities',

        'intl_gds_itinerary',
        'intl_pnr_child_infant',
        'intl_senior_citizen_fares',
        'intl_student_fares',
        'intl_youth_special_fares',
        'intl_fare_mask',
        'intl_gds_type',
        'intl_gds_other_name',
        'intl_queue_pnrs',
        'intl_first_reissue',
        'intl_subsequent_reissue',
        'intl_ticket_refunds',
        'intl_hotac_rooms',
        'intl_group_pnr',
        'intl_issue_emd',
        'intl_standalone_emd',
        'intl_associated_emd',
        'intl_mng_queues_upd_pnrs',

        'visa_aware_procedures',
        'visa_handled_personally',
        'visa_in_department',
        'visa_usa',
        'visa_canada',
        'visa_mexico',
        'visa_brazil',
        'visa_other_south_america',
        'visa_uk',
        'visa_ireland',
        'visa_haj_umrah',
        'visa_uae',
        'visa_schengen_countries',
        'visa_russia',
        'visa_china',
        'visa_vietnam',
        'visa_cambodia',
        'visa_hongkong',
        'visa_philippines',
        'visa_singapore',
        'visa_malaysia',
        'visa_australia',
        'visa_newzealand',
        'visa_draft_cover_note',

        'tours_handled_packages',
        'tours_countries',
        'tours_worked_cost',
        'tours_incentive_groups',
        'tours_mice_groups',
        'tours_cruise_pax',

        'acc_record_transactions',
        'acc_bank_cc_reconciliation',
        'acc_corporate_card_reconciliation',
        'acc_track_commissions',
        'acc_submit_invoices',
        'acc_manage_financial_records',
        'acc_software_excel_proficient',
        'acc_prepare_analyze_reports',
        'acc_ensure_compliance',
        'acc_manage_ap_ar',
        'acc_process_payroll_expenses',
        'acc_calculate_pay_taxes',
        'acc_coordinate_auditors',
        'acc_monitor_cashflow_forecast',
        'acc_reconcile_bsp',
    ];

    // Cast boolean-like string values (Yes/No) to actual booleans if needed
    protected $casts = [
        'not_want_company' => 'string',
        'domestic_gds_itinerary' => 'boolean',
        'domestic_pnr_adult' => 'boolean',
        'domestic_pnr_child_infant' => 'boolean',
        'domestic_senior_citizen_fares' => 'boolean',
        'domestic_student_fares' => 'boolean',
        'domestic_youth_special_fares' => 'boolean',
        'domestic_fare_mask' => 'boolean',
        'domestic_ticketing_gds' => 'boolean',
        'domestic_lcc_websites' => 'boolean',
        'domestic_supplier_portal' => 'boolean',
        'hotel_bookings_india' => 'boolean',
        'hotel_contact_direct' => 'boolean',
        'hotel_consolidator_websites' => 'boolean',
        'hotel_local_dmc' => 'boolean',
        'car_hire_city' => 'boolean',
        'car_hire_other_cities' => 'boolean',
        'intl_gds_itinerary' => 'boolean',
        'intl_pnr_child_infant' => 'boolean',
        'intl_senior_citizen_fares' => 'boolean',
        'intl_student_fares' => 'boolean',
        'intl_youth_special_fares' => 'boolean',
        'intl_fare_mask' => 'boolean',
        'intl_queue_pnrs' => 'boolean',
        'intl_first_reissue' => 'boolean',
        'intl_subsequent_reissue' => 'boolean',
        'intl_ticket_refunds' => 'boolean',
        'intl_hotac_rooms' => 'boolean',
        'intl_group_pnr' => 'boolean',
        'intl_issue_emd' => 'boolean',
        'intl_standalone_emd' => 'boolean',
        'intl_associated_emd' => 'boolean',
         'intl_mng_queues_upd_pnrs'=>'boolean',
       
        'visa_aware_procedures' => 'boolean',
        'visa_handled_personally' => 'boolean',
        'visa_in_department' => 'boolean',
        'visa_usa' => 'boolean',
        'visa_canada' => 'boolean',
        'visa_mexico' => 'boolean',
        'visa_brazil' => 'boolean',
        'visa_other_south_america' => 'boolean',
        'visa_uk' => 'boolean',
        'visa_ireland' => 'boolean',
        'visa_haj_umrah' => 'boolean',
        'visa_uae' => 'boolean',
        'visa_russia' => 'boolean',
        'visa_china' => 'boolean',
        'visa_vietnam' => 'boolean',
        'visa_cambodia' => 'boolean',
        'visa_hongkong' => 'boolean',
        'visa_philippines' => 'boolean',
        'visa_singapore' => 'boolean',
        'visa_malaysia' => 'boolean',
        'visa_australia' => 'boolean',
        'visa_newzealand' => 'boolean',
        'visa_draft_cover_note' => 'boolean',
        'tours_handled_packages' => 'boolean',
        'tours_worked_cost' => 'boolean',
        'tours_incentive_groups' => 'boolean',
        'tours_mice_groups' => 'boolean',
        'tours_cruise_pax' => 'boolean',
        'acc_record_transactions' => 'boolean',
        'acc_bank_cc_reconciliation' => 'boolean',
        'acc_corporate_card_reconciliation' => 'boolean',
        'acc_track_commissions' => 'boolean',
        'acc_submit_invoices' => 'boolean',
        'acc_manage_financial_records' => 'boolean',
        'acc_software_excel_proficient' => 'boolean',
        'acc_prepare_analyze_reports' => 'boolean',
        'acc_ensure_compliance' => 'boolean',
        'acc_manage_ap_ar' => 'boolean',
        'acc_process_payroll_expenses' => 'boolean',
        'acc_calculate_pay_taxes' => 'boolean',
        'acc_coordinate_auditors' => 'boolean',
        'acc_monitor_cashflow_forecast' => 'boolean',
        'acc_reconcile_bsp' => 'boolean',
        'willing_to_relocate' => 'boolean',
    ];
}